use std::collections::HashMap;

pub fn get_statistic_variable_tokens() -> HashMap<u8, String> {
    let tokens: HashMap<u8, String> = [
        (0x00, "internal use only".to_string()),
        (0x01, "RegEq".to_string()),
        (0x02, "[n]".to_string()),
        (0x03, "x̄".to_string()),
        (0x04, "Σx".to_string()),
        (0x05, "Σx²".to_string()),
        (0x06, "Sx".to_string()),
        (0x07, "\u{03c3}x".to_string()),
        (0x08, "minX".to_string()),
        (0x09, "maxX".to_string()),
        (0x0A, "minY".to_string()),
        (0x0B, "maxY".to_string()),
        (0x0C, "ȳ".to_string()),
        (0x0D, "Σy".to_string()),
        (0x0E, "Σy²".to_string()),
        (0x0F, "Sy".to_string()),
        (0x10, "\u{03c3}y".to_string()),
        (0x11, "Σxy".to_string()),
        (0x12, "[r]".to_string()),
        (0x13, "Med".to_string()),
        (0x14, "Q₁".to_string()),
        (0x15, "Q₃".to_string()),
        (0x16, "[a]".to_string()),
        (0x17, "[b]".to_string()),
        (0x18, "[c]".to_string()),
        (0x19, "[d]".to_string()),
        (0x1A, "[e]".to_string()),
        (0x1B, "x₁".to_string()),
        (0x1C, "x₂".to_string()),
        (0x1D, "x₃".to_string()),
        (0x1E, "y₁".to_string()),
        (0x1F, "y₂".to_string()),
        (0x20, "y₃".to_string()),
        (0x21, "𝑛".to_string()),
        (0x22, "[p]".to_string()),
        (0x23, "[z]".to_string()),
        (0x24, "[t]".to_string()),
        (0x25, "χ²".to_string()),
        (0x26, "𝙵".to_string()),
        (0x27, "df".to_string()),
        (0x28, "p̂".to_string()),
        (0x29, "p̂₁".to_string()),
        (0x2A, "p̂₂".to_string()),
        (0x2B, "x̄₁".to_string()),
        (0x2C, "Sx₁".to_string()),
        (0x2D, "n₁".to_string()),
        (0x2E, "x̄₂".to_string()),
        (0x2F, "Sx₂".to_string()),
        (0x30, "n₂".to_string()),
        (0x31, "Sxp".to_string()),
        (0x32, "lower".to_string()),
        (0x33, "upper".to_string()),
        (0x34, "[s]".to_string()),
        (0x35, "r²".to_string()),
        (0x36, "R²".to_string()),
        (0x37, "Factor df".to_string()),
        (0x38, "Factor SS".to_string()),
        (0x39, "Factor MS".to_string()),
        (0x3A, "Error df".to_string()),
        (0x3B, "Error SS".to_string()),
        (0x3C, "Error MS".to_string()),
    ]
    .iter()
    .cloned()
    .collect();

    tokens
}
