use std::collections::HashMap;

pub fn get_window_and_finance_tokens() -> HashMap<u8, String> {
    let tokens: HashMap<u8, String> = [
        (0x00, "ZXscl".to_string()),
        (0x01, "ZYscl".to_string()),
        (0x02, "Xscl".to_string()),
        (0x03, "Yscl".to_string()),
        (0x04, "u(nMin)".to_string()),
        (0x05, "v(nMin)".to_string()),
        (0x06, "Un-1".to_string()),
        (0x07, "Vn-1".to_string()),
        (0x08, "Zu(nMin)".to_string()),
        (0x09, "Zv(nMin)".to_string()),
        (0x0A, "Xmin".to_string()),
        (0x0B, "Xmax".to_string()),
        (0x0C, "Ymin".to_string()),
        (0x0D, "Ymax".to_string()),
        (0x0E, "Tmin".to_string()),
        (0x0F, "Tmax".to_string()),
        (0x10, "thetaMin".to_string()),
        (0x11, "thetaMax".to_string()),
        (0x12, "ZXmin".to_string()),
        (0x13, "ZXmax".to_string()),
        (0x14, "ZYmin".to_string()),
        (0x15, "ZYmax".to_string()),
        (0x16, "Zthetamin".to_string()),
        (0x17, "Zthetamax".to_string()),
        (0x18, "ZTmin".to_string()),
        (0x19, "ZTmax".to_string()),
        (0x1A, "TblStart".to_string()),
        (0x1B, "PlotStart".to_string()),
        (0x1C, "ZPlotStart".to_string()),
        (0x1D, "nMax".to_string()),
        (0x1E, "ZnMax".to_string()),
        (0x1F, "nMin".to_string()),
        (0x20, "ZnMin".to_string()),
        (0x21, "DeltaTbl".to_string()),
        (0x22, "Tstep".to_string()),
        (0x23, "thetastep".to_string()),
        (0x24, "ZTstep".to_string()),
        (0x25, "Zthetastep".to_string()),
        (0x26, "DeltaX".to_string()),
        (0x27, "DeltaY".to_string()),
        (0x28, "XFact".to_string()),
        (0x29, "YFact".to_string()),
        (0x2A, "TblInput".to_string()),
        (0x2B, "|N".to_string()),
        (0x2C, "I%".to_string()),
        (0x2D, "PV".to_string()),
        (0x2E, "PMT".to_string()),
        (0x2F, "FV".to_string()),
        (0x30, "|P/Y".to_string()),
        (0x31, "|C/Y".to_string()),
        (0x32, "w(nMin)".to_string()),
        (0x33, "Zw(nMin)".to_string()),
        (0x34, "PlotStep".to_string()),
        (0x35, "ZPlotStep".to_string()),
        (0x36, "Xres".to_string()),
        (0x37, "ZXres".to_string()),
        (0x38, "TraceStep".to_string()),
    ]
    .iter()
    .cloned()
    .collect();

    tokens
}
